# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 09:56
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('core', '0003_remove_dish_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='ingredient',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
