# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dish_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
